### ISSUE TITLE
cellxgene-schema must validate that -add-labels will not result in a write failure during ingestion

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#405] opened 2023-03-15 20:35 UTC
There have been multiple instances where a validated dataset has been uploaded to CELLxGENE Discover and then fails during -`add-labels` with an exception like:

`
ERROR: Writing h5ad was unsuccessful, got exception 'Can't implicitly convert non-string objects to string'. Above error raised while writing key 'categories' of <class 'h5py._hl.group.Group'> to /'."
`

See [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1675282747137719)
See [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1677766575087969). 
See [**single-cell-data-representation**](https://cziscience.slack.com/archives/C01L65J7PLP/p1678805519018689). 

@jychien has shared a mitigation with other curators:

> I used cellxgene-schema validate --add-labels output_file input_file to trouble shoot the dataset.

**UPDATE:**
Note to assignee from Nayib:
Our own testing/QA would catch if these errors were being introduced by the add-labels step, as those changes are entirely deterministic. Most likely, these scenarios occur when the dataset is already malformed when initially submitted. The errors are triggered by the add-label step because it's the only time we attempt to write to a file, exposing some existing defect on the dataset that our validation does not check for. Consider that when trying to create a test file to validate this during QA, Jenny (see comment below) was not able to because the call to 'anndata.write' throws the aforementioned error and didn't allow her to create the test file.

I think something similar to introducing a dry-run write to a 'dummy' temp file could catch and return these errors during the validate step; however, if we go this route, we should alert users about this write+delete to a temp file while validating locally. And consider memory/performance implications.

**Comment by jychien** [comment] 2023-09-18 16:26
I am not able to create and write to file another AnnData with the same error for obs having a categorical column containing boolean objects. The same error is given when I write the AnnData to file. I have the [original h5ad](https://drive.google.com/file/d/1ixLnCUAHeV89Bp-gpu7o10-uiPwfcJkt/view?usp=sharing) file that the original curator (Batu) had come across and can test with this file. However, this h5ad file is formatted to schema 3.0, and therefore we will need to stage the testing for this ticket differently. Thanks!

**Comment by Bento007** [comment] 2023-09-21 23:12
The error mentioned above might get fix in annadata 0.10.0 https://github.com/scverse/anndata/issues/726#issuecomment-1711388396

**Comment by Bento007** [comment] 2023-09-22 00:04
I tried the naive approach of trying to write the dataset to a temp directory during validation. It worked ok for small datasets, but for our larger datasets it exploded in memory usage as well as time.

**Comment by Bento007** [comment] 2023-09-22 00:08
It's difficult to detect where this('Can't implicitly convert non-string objects to string') will occur, since it can happen in any of the matrixes. I'm going to try installing https://github.com/scverse/anndata and see if the head branch has a fix. It sounds like it will be released soon.

**Comment by Bento007** [comment] 2023-09-22 20:56
> I am not able to create and write to file another AnnData with the same error for obs having a categorical column containing boolean objects. The same error is given when I write the AnnData to file. I have the [original h5ad](https://drive.google.com/file/d/1ixLnCUAHeV89Bp-gpu7o10-uiPwfcJkt/view?usp=sharing) file that the original curator (Batu) had come across and can test with this file. However, this h5ad file is formatted to schema 3.0, and therefore we will need to stage the testing for this ticket differently. Thanks!

@brianraymor I verified that in anndata 0.10.0 this problem has been fixed using the original h5ad mentioned. This wont catch these types of error earlier, but prevent them all together. Migrating to anndata 0.10.0 is likely a heavier lift then we want to take on at the moment, but it is an option. 

The plan for now is add a flag to the CLI to allow curator to run a more thorough validation which will attempt to write the file out. This requires reading into memory and will require disk space to write the temporary file. This will not be the default behavior and a warning about time and resources required will be in both the description and when the command is executed.

**Comment by brianraymor** [comment] 2023-09-22 21:04
I appreciate the research and update @Bento007. 

anndata 0.10.0 is a release candidate too so that's another reason that we would not to adopt at this time. Generally, we update anndata versions when the curators start receiving new(er) versions of anndata datasets from submitters.

**Comment by Bento007** [comment] 2023-09-23 00:21
For the specific case of the dataset above:
In:
```
adata.obs["is_doublet"]
```
Out:
```
Name: is_doublet, Length: 191230, dtype: category
Categories (2, object): [False, True]
```

`anndata.write_h5ad` does not like that the catagories are boolean.

During the add labels step we could go through all of the columns and make sure that any Catagory columns are strings.

**Comment by Bento007** [comment] 2023-09-25 22:15
I've identified two cases where we could fail writing the h5ad. One was derived from the anndata github issue mention above. The other was derived from the dataset mentioned above. Here are the two causes:

- Having mixed types in a column
- Having none string values for catagories

Checks for these cases will be added to the validator. This may not be all of the causes, but some of these have been fixed in anndata 0.10.0

**Comment by Bento007** [comment] 2023-09-28 23:40
@jahilton @corismall read for QA

**Comment by jahilton** [comment] 2023-09-29 00:33
We only know 1 case that should newly fail because of this update, and we can't change it because AnnData fails to write it.
This does now produce a new error based on this update, in addition to other errors from the file prepared for a previous schema version
`ERROR: Column 'is_doublet' in dataframe 'obs' must only contain string categories. Found {<class 'bool'>}.`
And we trust that had the other issues (uns.schema_version & obs.tissue_type) been correct, the is_doublet error would have alone failed validation.
So Good-2-Go

[QA notebook](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/405_category_of_bool.ipynb)

**Closed** 2023-09-29 16:27 UTC
Labels: curation software, P0, 4.0, dp
